// useHero.js
import { reactive, ref } from 'vue';


const hero = ref({
  hp: 100,
  maxHp: 100,
  attack: 10,
  def: 0,
  crit: 0,
  critAttack: 1.5,
  level: 0,
  eLevel: 1,
  minLevel: 0,
  maxReachedLevel: 0,
  divLevel: 0,
  maxLevel: 30,
  trueLevel: 0,
  exp: 0,
  totalExp: 0,
  nextLevelExp: 100,
  attacksPerSecond: 0.5,
  resetKilledTime: 0,
  kills: 0,
  killsPerZone: 5,
  zone: 1,
  stage: 1,
  maxStage: 1,
  isStage: true,
  isBattleActive: true,
  overkill: 0,
  treeTier: 0,
  perkPoints: 0,
  eqTotalDrop: 0,
  equipmentTiers: {
    sword: 0,
    armor: 0,
    boots: 0,
    ring: 0,
    spRing: 0
  },
  eqTierReq: {
    sword: 3,
    armor: 3,
    boots: 3,
    ring: 0,
    spRing: 0
  },
  eqMin: {
    sword: 0,
    armor: 0,
    boots: 0,
    ring: 0,
    spRing: 0
  },
  eqDrop: {
    sword: 0,
    armor: 0,
    boots: 0,
    ring: 0,
  },
  eqUps: {
    sword: 0,
    armor: 0,
    boots: 0,
    ring: 0,
    spRing: 0
  },
  eqUpsMult: {
    sword: {
      cap: 0,
      bonus: 0,
      crit: 0,
      critDmg: 0
    },
    armor: {
      cap: 0,
      bonus: 0,
      def: 0,
      heal: 0,
    },
    boots: {
      cap: 0,
      bonus: 0,
      stage: 0,
      overkill: 0,
    },
    ring: {
      cap: 0,
      bonus: 0,
      level: 1,
      multLevel: 0,
    },
    spRing: {
      cap: 0,
      bonus: 0
    }
  },
  awakened: {
    sword: 0,
    armor: 0,
    boots: 0,
    ring: 0
  },
  dropChance: {
    sword: 0,
    armor: 0,
    boots: 0,
    ring: 0
  },
  shardsMult: 0,
  shardsPerformMult: 0,
  ascensionShards: 0,
  totalAscensionShards: 0,
  isAscend: false,
  ascendShardPerform: 0,
  ascensionTier: 1,
  maxBuffs: 1,
  activeBuffs: [],
  souls: 0,
  soulsMax: 0,
  soulsCap: 20,
  soulTier: 0,
  curse: 0,
  activeCurse: [],
  activeCurseTier: [],
  cursedBonus: 0,
  cursedBonusExp: 0,
  afkTime: 0,
  showAfkPopup: false,
  afkKills: 0,
  afkMessage: "",
  showAfkPopupRule: true,
  isRebirth: false,
  rebirthPts: 0,
  totalRebirthPts: 1,
  rebirthTier: 0,
  totalPtsMult: 0,
  potential: 0,
  avoid: 0,
  activeFormation: null,
  formationTypes : [
    { name: 'HP', id: 0, icon: '💚', description: 'HP - x2, ATK - x0.5, DEF - x0.5',status: false },
    { name: 'Attack', id: 1, icon: '⚔️', description: 'ATK - x2, HP - x0.5, DEF - x0.5' , status: false},
    { name: 'Defense', id: 2, icon: '🛡️', description: 'DEF - x2, HP - x0.5, ATK - x0.5' , status: false},
    { name: 'Loot', id: 3, icon: '💎', description: 'DEF - x0.5, HP - x0.5, ATK - x0.5, LOOT: 2(EXP, BUFF EXP, WEAPON CHANCE, ASCENSION SHARDS(Abyss [T2]))' , status: false},
  ],
  abyssTier: 0,
  isAbyss: false,
  perform: false,
  isLocking: false,
  isLocked: false,
  afkLocked: false,
  mutation: [
    {type: 'Mutation [T1]', chance: 25 },
    {type: 'Mutation [T2]', chance: 10},
    {type: 'Mutation [T3]', chance: 0},
    {type: 'Mutation [T4]', chance: 0},
  ],
  mutagen: 0,
  sp: 0,
  st: 0,
  spCount: 0,
  spMaxCount: 24,
  stardust: 0,
  corruption: 0.1,
  spaceFight : false,
  abyssDStages: 1,
  infPoints: 0,
  infPointsGoals: 0,
  infTier: 0,
  maxInfTier: 0,
  infTree: false,
  soulD: false,
  treeAuto: false,
  isSpaceBuff: false,
  spActiveBuffs: [],
  isSpaceAuto: false,
  spBossPerk: 0,
  afkSoulBoost: 1,
  capInfPerks: 1,
  mutations: 0,
  infProgress: true,
  infoActive: {
    lore: true,
    tree: true,
    equipment: false,
    buffs: false,
    souls: false,
    ascension: false,
    corruption: false,
    amulet: false,
    rebirth: false,
    abyss: false,
    space: false,
    radiation: false,
    infinity: false,
    singularity: false,
    dimensions: false,
    stats: true
  },
  singularity: 0,
  isSingularity: false,
  overcorruption: 0,
  freeEnchances: 0,
  isDimension: false,
  dId: 'main',
  mainInfTier: 0,
  survivalLevel: 0,
  windowUpdate: false,
  freeTreePoints: 0,
  unlimitLevel: 0,
  gcnpSetting: false,
  singularityAscension: [],
  singularitySpace: {
    sp: 0,
    st: 0,
    spCount: 0,
  },
  singularityRingUp: 0, 
  singularityRebirthTier: 0,
  afkTimer: 0,
  afkMaxTimer: 14400,
  afkSpendPercent: 0,
  enemyAfkHp: 1,
  travellPenalty: 1,
  isTravell: false,
  ascensionAuto: false,
  ascensionAutoUnlock: false,
  afkTimeHandle: 1,
  singularityKills: 0,
  curset5: false,
  curset5Chance: 0,
  soulOverkill: 0,
  soulDStage: 0,
  ds: 0,
  dsSpend: 0,
  dsMax: 0,
  dsTotal: 0,
  infPenalty: 0,
  dangerStage: 0,
  dsStage: 150,
  dTimeReward: 0,
  dTimer: 0,
  dTimeReward: 0,
  abyssDStagesMax: 100,
  dKills: 0,
  survivalStage: 0,
  curseMult: 1,
  infPointsMult: 1,
  baseSp: 0,
  eLink: {
    set: '',
    info: '',
    stat: '',
  },
  secrets: {
    travell: false,
    time: false,
    link: false,
    dLink: false,
    dLore: false,
    dView: true,
  },
  maxLevelMult: 0,
  stardustInfo: 0,
  timeKiller: 0,
});

export function useHero() {
  return { hero };
}
